Fix/old testing disable ssh test (#3876)
In this commit, we disable the test_sshd for the FIPS feature. When running on the old testing frame with a FIPS-enabled flavor, we receive error messages when testing.

    FAILED ssh/test/test_sshd.py::test_sshd[KexAlgorithms sntrup761x25519-sha512,sntrup761x25519-sha512@openssh.com,mlkem768x25519-sha256,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521] - AssertionError: [('kexalgorithms', {'curve25519-sha256', 'ecdh-sha2-nistp521', 'curve25519-sha256@libssh.org', 'sntrup761x25519-sha512', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'sntrup761x25519-sha512@openssh.com', 'mlkem768x25519-sha256'})] not found in sshd_config
    FAILED ssh/test/test_sshd.py::test_sshd[Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com] - AssertionError: [('ciphers', {'aes192-ctr', 'aes256-gcm@openssh.com', 'aes128-gcm@openssh.com', 'aes256-ctr', 'chacha20-poly1305@openssh.com', 'aes128-ctr'})] not found in sshd_config


This also includes a missing alteration for the SSH configuration cipher chacha20-poly1305@openssh.com for chroot, since it won't work in a FIPS environment. Without the connection, it might fail, since the chroot isn't able to start. 

This commit was squashed:

* Disable chacha20-poly1305@openssh.com for chroot, since it won't work in a FIPS environment.
* Add non_fips fixture to conftest
* Exclude test_sshd in the old testing framework when running FIPS

Relates: #3436