Set OPENSSL_MODULES to load fips.so
The python version is missing path to load the fips.so provider.
Without we will receive:

    _hashlib.UnsupportedDigestmodError: [digital envelope routines]
unsupported

When loading support hash function like SHA256.