Revert "Merge pull request #3489 from gardenlinux/test/migrate-test-time-config" (#3888)
This reverts commit aa2d377f24095027ddecceb217ca8c88b627a741, reversing
changes made to 5a5154c6059836396dbb585501689768f8f8eb61.

This breaks the nightly with this error on gcp

```
FAILED test_time_config.py::test_clocksource_amd64 - AssertionError: unknown hypervisor Hypervisor.google
FAILED test_time_config.py::test_clocksource_arm64_aarch64 - AssertionError: unknown hypervisor Hypervisor.google
```

cf https://github.com/gardenlinux/gardenlinux/actions/runs/19360448813/job/55400679661#step:19:1603